# Generated by Django 5.0.7 on 2024-07-19 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_plate', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='oficina.car')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficina.mechanical')),
            ],
        ),
    ]
