# Generated by Django 5.0.7 on 2024-07-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
