# Generated by Django 5.0.7 on 2024-07-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_rename_create_at_service_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
